### ISSUE TITLE
Inconsistência no arquivo images/descritiva/poligono.R

### ISSUE THREAD

**Issue by edusantana** [ufpb-computacao/estatistica-livro#2]
Oi @dearocha,

Eu fiz uma checagem por alto, apenas para verificar a compilação dos seus arquivos R.

Então percebi que o arquivo `images/descritiva/poligono.R` não está compilando.

O que me fez pensar que talvez o gráfico gerado esteja inconsistente com o desejado. 

Você poderia atualizá-lo?

**Comment by dearocha** [comment]
Olá Eduardo,

O gráfico gerado está ok. Já ajeitei o fonte, era só um detalhe.
